# Generated by Django 3.1.5 on 2021-02-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210207_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='session_id',
            field=models.CharField(max_length=100),
        ),
    ]
