# Generated by Django 3.1.5 on 2021-02-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customer_user'),
        ('users', '0003_auto_20210210_1904'),
    ]

    operations = [
    ]
