# Generated by Django 3.1.5 on 2021-02-05 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
