# Generated by Django 3.1.5 on 2021-02-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('clothing', 'clothing'), ('notebooks', 'notebooks'), ('computers', 'computers'), ('smartphones', 'smartphones'), ('tablets', 'tablets'), ('headphones', 'headphones'), ('cameras', 'cameras')], max_length=15)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='public/assets')),
                ('image_name', models.CharField(default='default.jpg', max_length=50)),
                ('label', models.CharField(blank=True, choices=[('New', 'New'), ('Bestseller', 'Bestseller')], max_length=10, null=True)),
                ('label_color', models.CharField(blank=True, choices=[('blue', 'blue'), ('red', 'red')], max_length=10, null=True)),
            ],
        ),
    ]
