# Generated by Django 3.1.5 on 2021-02-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='include',
            field=models.BooleanField(default=True),
        ),
    ]
