# Generated by Django 3.1.5 on 2021-01-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210127_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageName',
            field=models.CharField(default='default.jpg', max_length=20),
        ),
    ]
