# Generated by Django 3.1.5 on 2021-01-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_imagename'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label_color',
            field=models.CharField(blank=True, choices=[('blue', 'blue'), ('red', 'red')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Shirt', 'Shirt'), ('Sport wear', 'Sport wear'), ('Outwear', 'Outwear')], max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='frontend/assets/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Bestseller', 'Bestseller')], max_length=10, null=True),
        ),
    ]
