# Generated by Django 3.1.5 on 2021-02-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210128_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothing', 'clothing'), ('notebooks', 'notebooks'), ('computers', 'computers'), ('smartphones', 'smartphones'), ('tablets', 'tablets'), ('headphones', 'headphones'), ('cameras', 'cameras')], max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='imageName',
            field=models.CharField(default='default.jpg', max_length=50),
        ),
    ]
