# Generated by Django 3.1.5 on 2021-02-10 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210204_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imageName',
            new_name='image_name',
        ),
    ]
